name: Build Rive framework

on:
  push
  # push:
  #   tags:
  #     - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RIVE_REPO_PAT }}
          submodules: recursive
      - name: Init submodule
        run: git submodule update --init
      - name: Build Android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew kotlin:assembleRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rive
          path: kotlin/build/outputs/aar/kotlin-release.aar
