name: Build Rive framework

on:
  push
  # push:
  #   tags:
  #     - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RIVE_REPO_PAT }}
          submodules: recursive
      - name: Init submodule
        run: git submodule update --init

      # Download & install the Android SDK.
      - name: Set up Android
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      # Set up platform tools like adb.
      - run: sdkmanager platform-tools
      - name: Build Android
        # Download & install the Android SDK.
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.1
        with:
          cmd: ./gradlew kotlin:assembleRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rive
          path: kotlin/build/outputs/aar/kotlin-release.aar
